#! /bin/bash

TEMPLATES="${HOME}/projects/tex-macros/templates/moderncv/"

template() {
echo '
\documentclass[11pt,executivepaper]{moderncv}

\usepackage[inline]{enumitem}
\usepackage{xcolor}
\usepackage[osf]{garamondx}
\moderncvstyle{oldstyle}
\moderncvcolor{purple}
\usepackage[scale=0.8]{geometry}
%----------------------------------------------------------------------------------------
\firstname{}
\familyname{}

\title{Person of Interest}
\address{}{}
\phone{}
\email{}
\homepage{}{}
%\extrainfo{additional information}
\photo[150pt][1pt]{sample-picture.jpg} % The first bracket is the picture height, the second is the thickness of the frame around the picture
\quote{}
%----------------------------------------------------------------------------------------
\begin{document}
	\makecvtitle
	%----------------------------------------------------------------------------------------
	\section{Education}
	
	\cventry{}{}{}{}{}{}%year, type of education, institute, location, location, study
	
	
	\section{Interpersonal Relations}
	
	\subsection{Relevant Family}
	
	\cventry{}{}{}{}{}{}%type of relative, name of relative, nothing, nothing, nothing, description of their relationship
	
	
	\subsection{Relevant Friends}
	
	\cventry{}{}{}{}{}{}%type of friend, name of friend, nothing, nothing, nothing, description of their relationship
	
	%----------------------------------------------------------------------------------------
	
	\section{Habits}
	\renewcommand{\labelitemi}{\raisebox{1.5pt}{\includegraphics[width=6pt]{teapot.png}}~}
	
	\cvlistdoubleitem{}{}%habit, note(s) on habit
	
	%----------------------------------------------------------------------------------------
	
	\section{Hopes and Aspirations}
	
	\cvitem{}{}
	
	%----------------------------------------------------------------------------------------
	
	\section{Interests}
	
	\renewcommand{\listitemsymbol}{\raisebox{1.5pt}{\includegraphics[width=6pt]{teapot.png}}~} % Changes the symbol used for lists
	
	\cvlistdoubleitem{}{}%item one, item two
	\cvlistitem{}%item three
	
	%----------------------------------------------------------------------------------------
	
\end{document}

'
}

mkdir "poi_$1"

for f in "${TEMPLATES}"*.sty
do
    cp -fr $f ./poi_$1
done

cp "${TEMPLATES}moderncv.cls" "./poi_$1/"
cp "${TEMPLATES}/sample-picture.jpg" "./poi_$1/"
cp "${TEMPLATES}/teapot.png" "./poi_$1/"

touch "./poi_$1/poi_$1.tex" && template >> ./poi_$1/poi_$1.tex

open -a "TeXStudio.app" "poi_$1/poi_$1.tex"

