#! /bin/bash

size_of_dir() { 
    DIR_SIZE=$(find "${1}" ! -type d -print0 | xargs -0 stat -f '%z' | awk '{sum += $1} END{print sum}')  # Finds total space taken up by dir in bytes.  Not my own code: https://unix.stackexchange.com/a/177371/372726
    echo "${DIR_SIZE}" 
    }
    
    
human_readable_bytes() {
    if [[ $1 -ge 0 ]] && [[ $1 -lt 1000 ]]
    then
        SIZE="${1}"
        TYPE="B"
    elif [[ $1 -ge 1000 ]] && [[ $1 -lt 1000000 ]]
    then
        SIZE=$(echo "$((${1} / 1000))")
        TYPE="KB"
    elif [[ $1 -ge 1000000 ]] && [[ $1 -lt 1000000000 ]]
    then
        SIZE=$(echo "$((${1} / 1000000))")
        TYPE="MB"
    elif [[ $1 -ge 1000000000 ]] && [[ $1 -lt 1000000000000 ]]
    then
        SIZE=$(echo "$((${1} / 1000000000))")
        TYPE="GB"
    elif [[ $1 -gt 1000000000000 ]]
    then
        SIZE=$(echo "$((${1} / 1000000000000))")
        TYPE="TB"
    fi
    echo "${SIZE} ${TYPE}"
}

size_of_dir .
