[package]
name = "bats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
battery = "0.7.8"
clap = { version = "4.0.22", features = ["cargo", "wrap_help", "derive"] }

