[package]
name = "rusty_ls"
version = "0.1.0"
authors = ["jakewilliami <jakewilliami@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.14"
chrono = "0.4.9"
walkdir = "2.3.1"
