[package]
name = "filmls"
version = "1.5.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.22", features = ["cargo", "wrap_help", "derive"] }
colored = "2.0.0"
regex = "1.7.0"
