[package]
name = "foodle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trillium = "0.2"
trillium-smol = "0.2"
trillium-router = "0.2.0"
