[package]
name = "winphysec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
clap = { version = "4.0.29", features = ["cargo", "wrap_help", "derive"] }
dotenv = "0.15.0"
reqwest = "0.11.13"
serde_json = "1.0.89"
tokio = { version = "1.22.0", features = ["full"] }
