#! /bin/bash

# define bash directory
BASH_DIR="${HOME}"/scripts/bash/

# source required scripts
source "${BASH_DIR}"/dependencies/source-dependencies.sh

# get dependencies regardless of kernel and os
is-command-then-install "${PERL_PACKAGE}"

# Help
display_help() { #Displays help
    help_start 'applications [option...]' 'The present script will create system information in \`~/scripts/perl\` regarding applications and use them to find the applications which are not managed by the Mac App Store or Homebrew.'
    help_commands '-a' '--list-applications' '1' 'Lists' 'a' 'pplications' 'that are not from the app store or made by Apple.'
    help_commands '-b' '--list-brew' '2' 'Lists' 'b' 'rew' 'casks.'
    help_commands '-c' '--compile' '3' '\b' 'C' 'ompiles' 'data from applications and saves as text in \`~/scripts/perl\`.'
    help_help '3'
    clean-exit
}

# Compile .txt files for casks, applications, and process system_profiler -xml
perl_compile() {
    perl -X ${HOME}/scripts/perl/applications.pl || exit $?
}

list_applications() {
    cat ${HOME}/scripts/perl/temp.d/dataApps.txt | cut -f1 -d":" | sed 's/[0-9]*$//' | sed 's/-$//' | awk '{$1=$1;print}'
}

list_casks() {
    cat ${HOME}/scripts/perl/temp.d/casks.txt | awk '{ gsub ("-", " ", $0); print}'
}


# Options
while getopts ":-:abch" OPTION
do
        case $OPTION in
                -)  #Long options for bash (without GNU)
                    case $OPTARG in
                        list-applications)
                            perl_compile && \
                            list_applications ;;
                        list-brew)
                            perl_compile && \
                            list_casks ;;
                        help)
                            display_help ;;
                        compile)
                            perl_compile && \
                    echo -e "${BGREEN}Successfully compiled application data in \`~/scripts/perl\`.${NORM}";;
                        *)
                            opt_err ;;
                    esac ;;
                a)
                    perl_compile && \
                    list_applications ;;
                b)
                    perl_compile && \
                    list_casks ;;
                c)
                    perl_compile && \
                    echo -e "${BGREEN}Successfully compiled Homebrew casks in \`~/scripts/perl/casks.txt\` and application data (minus app store and Apple data) in \`~/scripts/perl/dataApps.txt\`.${NORM}";;
                h)  
                    display_help ;;
                *)  
                    opt_err ;;
        esac
done
