#! /bin/bash


BASH_DIR="${HOME}/bin/scripts/bash/"

# Ensure jq is installed
source ${BASH_DIR}/dependencies/jq-dep.sh

# Colours
source ${BASH_DIR}/colours/json-colour-parser.sh

# Brew Install function
source ${BASH_DIR}/dependencies/brew-install-dep.sh

# Satisfy Dependencies
brew_install "${SATISFYING_DEPS}" ruby rbenv ruby-build && \
echo -e "${DEPS_SATISFIED}"

# Gem Install function
source ${BASH_DIR}/dependencies/gem-install-dep.sh

# Install dependencies
gem_install iStats

# Help
display_help() {
    echo -e "${BWHITE}Usage: cstatus [option...]${NORM}"
    echo
    echo -e "${ITWHITE}The present script will tell the user computer status/information given an option.${NORM}"
    echo
    echo -e "${BBLUE}\t -u | --cpu-util \t${BYELLOW}Prints total ${ULINE}${BBLUE}u${BYELLOW}tilisation${NORM}${BYELLOW} of the CPU in %.${NORM}"
    echo -e "${BBLUE}\t -s | --cpu-stats \t${BYELLOW}Prints CPU ${ULINE}${BBLUE}s${BYELLOW}tatistic${NORM}${BYELLOW} information.${NORM}"
    echo -e "${BBLUE}\t -e | --cpu-extended \t${BYELLOW}Prints ${ULINE}${BBLUE}e${BYELLOW}xtended${NORM}${BYELLOW} CPU information.${NORM}"
    echo -e "${BBLUE}\t -g | --geo-ip \t\t${BYELLOW}Shows ${ULINE}${BBLUE}g${BYELLOW}eo-location${NORM}${BYELLOW} information based on  my (current) ip address.${BNORM}"
    echo -e "${BBLUE}\t -h | --help \t\t${BYELLOW}Shows ${ULINE}${BBLUE}h${BYELLOW}elp${NORM} ${BYELLOW}(present output).${NORM}"
    clean-exit
}


opt_err() {
    HELP="${BYELLOW}Invalid option.  Use option -h for help.${NORM}"
    echo -e "${HELP}"
	clean-exit
}


opt_err_none() { #Invalid option (getopts already reported the illegal option)
    HELP="${BYELLOW}You must have at least one arguments.  Use -h for help.${BNORM}"
    echo -e "${HELP}"
	clean-exit
}


cpu_utilisation() {
    ps -A -o %cpu | \
    awk '{s+=$1} END {print s "%"}'  # Adds up all processes using cpu
}


cpu_statistics() {
    istats
}


cpu_extended() {
    istats extra
}


ip_specs() {
    output_type="${1}"  # Can interpret json, xml, and csv
    curl -s "https://freegeoip.app/${output_type}/${2}" | jq .
}


my_ip() {
    myip=$(curl -s http://checkip.dyndns.org/ | sed 's/[a-zA-Z<>/ :]//g')  # Get ip address
    grepped_ip=${myip%$'\r'}  # Remove end of line character from ip address
    ip_specs "json" "${grepped_ip}"
}


while getopts ":-:ughse" OPTION; do
        case $OPTION in
                -)
                    case $OPTARG in
                        geo-ip)
                            my_ip ;;
                        cpu-util)
                            cpu_utilisation ;;
                        cpu-stats)
                            cpu-statistics ;;
                        cpu-extended)
                            cpu_extended ;;
                        help)
                            display_help ;;
                        *)
                            opt_err ;;
                    esac ;;
                g)
                    my_ip ;;
                u)
                    cpu_utilisation ;;
                s)
                    cpu_statistics ;;
                e)
                    cpu_extended ;;
                h)  
                    display_help ;;
                *)
                    opt_err ;;
        esac
done


if [[ -z $1 ]]
then
    opt_err_none
fi


# Clean up
clean-exit
