#! /bin/bash

#Define local variables
REPLACING_TEX="\033[01;31mReplacing outdated .tex file(s) in git repository.\033[0;38m"
COMPLETED_TEX="\033[1;38;5;2m.tex transfer complete.\033[0;38m"
REPLACING_JSON="\033[01;33mReplacing outdated .json file(s) in git repository.\033[0;38m"
COMPLETED_JSON="\033[1;38;5;2m.json transfer complete.\033[0;38m"
ALL_GOOD_TEX="\033[1;38;5;2mYour git repository's templates directory's .tex files are up to date with your local templates directory.\033[0;38m"
ALL_GOOD_JSON="\033[1;38;5;2mYour git repository's templates directory's .json files are up to date with your local templates directory.\033[0;38m"

GIT_LOCATION="/Users/jakeireland/Documents/my_macros/"

LOCAL_DIR="${GIT_LOCATION}../../.config/texstudio/templates/user/"
GIT_DIR="${GIT_LOCATION}tea_templates/"

DIFFT=false
DIFFJ=false

#Begin script

cd "${GIT_LOCATION}" || exit $?

#check tex files
for t in "${LOCAL_DIR}"/*.tex; do
   if ! cmp -s "$t" "${GIT_DIR}"/$(basename $t)
   then
        DIFFT=true
        echo -e "${REPLACING_TEX}" 
        cp -fr "$t" "${GIT_DIR}/" && echo -e ${COMPLETED_TEX}
    fi
done

if [ $DIFFT = false ]
then
    echo -e "${ALL_GOOD_TEX}"
fi


for j in "${LOCAL_DIR}"/*.json; do
   if ! cmp -s "$j" "${GIT_DIR}"/$(basename $j)
   then
        DIFFJ=true
        echo -e "${REPLACING_JSON}" 
        cp -fr "$j" "${GIT_DIR}/" && echo -e ${COMPLETED_JSON}
    fi
done

if [ "$DIFFJ" = "false" ]
then
    echo -e "${ALL_GOOD_JSON}"
fi