#! /bin/bash

#Define local variables
REPLACING="\033[01;31mReplacing outdated .tex and .json in git repository.\033[0;38m"
COMPLETED="\033[1;38;5;2mTransfer complete.\033[0;38m"
ALL_GOOD="\033[1;38;5;2mYour git repository's templates directory is up to date with your local templates directory connected to TeXStudio IDE.\033[0;38m"

GIT_LOCATION="/Users/jakeireland/Documents/my_macros"

LOCAL_DIR="/Users/jakeireland/.config/texstudio/templates/user/"
GIT_DIR="/Users/jakeireland/Documents/my_macros/tea_templates/"


#Begin script

cd "${GIT_LOCATION}" || exit $?

#check tex files
for t in *.tex; do
   if ! cmp -s "${LOCAL_DIR}"$t "${GIT_DIR}"$t 
   then
        echo -e "${REPLACING_TEX}"
        cp -fr "${LOCAL_DIR}"$t "${GIT_DIR}" || exit $? && echo -e "${COMPLETED_TEX}"
    else
        echo -e "${ALL_GOOD_TEX}"
    fi
done

#check json files
for j in *.json; do
   if ! cmp -s "${LOCAL_DIR}"$j "${GIT_DIR}"$j 
   then
        echo -e "${REPLACING_JSON}"
        cp -fr "${LOCAL_DIR}"$j "${GIT_DIR}" || exit $? && echo -e "${COMPLETED_JSON}"
    else
        echo -e "${ALL_GOOD_JSON}"
    fi
done