#! /bin/bash

trap "exit" INT

# define bash directory
BASH_DIR="${HOME}/scripts/bash/"

# source required scripts
source ${BASH_DIR}/dependencies/source-dependencies.sh

# Help
display_help() { #Displays help
    help_start 'maclogout [option...]' 'The present script will log out of the current user on a mac computer.'
    help_help '2'
    clean-exit
}


if [[ ! $KERNEL == "Darwin" ]]
then
    echo -e "${BYELLOW}This command is only works on macOS.${NORM}"
    clean-exit
fi


# Options
while getopts ":-:h" OPTION
do
        case $OPTION in
                -)  #Long options for bash (without GNU)
                    case $OPTARG in
                        help)
                            display_help ;;
                        *)
                            opt_err ;;
                    esac ;;
                h)  
                    display_help ;;
                *)  
                    opt_err ;;
        esac
done


my_logout() {
    USER_INFO=$(ps -Ajc | grep loginwindow | sed 's/[ \t]*\([0-9]\{1,\}\).*/\1/')
    USER_PID=$(echo $USER_INFO | sed 's/[^0-9]//g')
    USERNAME=$(echo $USER_INFO | sed 's/[^a-zA-Z]//g')
    echo -e "${BYELLOW}Logging out of user ${NORM}${BWHITE}${USERNAME}${NORM}${BYELLOW}.${NORM}"
    sudo kill ${USER_PID}
}


# If option empty
if [[ -z $1 ]]
then 
    my_logout
fi


# Clean up
clean-exit