#! /bin/bash

trap "exit" INT

# define bash directory
BASH_DIR="${HOME}/scripts/bash/"

# Immediately exits script if nothing is passed to it
if [[ -z "${@}" ]]
then
    HELP="\033[1;33m You must have at least one argument.  Use -h for help. \033[0;38m"
    echo -e "${HELP}"
    exit $?
fi

# source required scripts
source ${BASH_DIR}/dependencies/source-dependencies.sh

# get kernel- and os-specific dependencies
case $KERNEL in
    Darwin)
        is-library-then-install "${BREWCASK}"
        is-app-then-install "${ATOM}"
        ;;
    Linux)
        if ! command -v atom > /dev/null 2>&1
        then
            case $(getconf LONG_BIT) in
                64)
                    case $OS in
                        debian)
                            cd "${HOME}"/Downloads/
                            wget -qO - https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -
                            sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list' && \
                            sudo apt-get update && \
                            sudo apt-get install atom || echo -e "${ERROR_OCCURRED}"
                            ;;
                        arch)
                            aur_install "${ATOM}" 'https://aur.archlinux.org/cgit/aur.git/snapshot/atom-editor-git.tar.gz'
                            ;;
                    esac
                    ;;
                32)
                    echo -e "${BYELLOW}Sorry, you need to manually download Atom on 32-bit systems.${NORM}"
                    clean-exit
                    ;;
                *)
                    echo -e "${BRED}Unrecgnised architechture.  Please attempt to install Atom on your system.${NORM}"
                    clean-exit
                    ;;
            esac
        fi
        ;;
esac


display_help() {
    help_start 'oinb [option... | file name...]' 'The present script will open a specified file in Atom.app.  If the file is not found in the current directory, it will look for it in `~/scripts/bash`.'
    help_commands '-c' '--command' '2' 'Opens a specific' 'c' 'ommand' 'in Atom.'
    help_help '2'
    clean-exit
}


main() {
    for f in "${@}"
    do
        if [[ $KERNEL == "Linux" ]]
        then
            RUN_COMMAND="atom"
        elif [[ $KERNEL == "Darwin" ]]
        then
            RUN_COMMAND="open -a /Applications/Atom.app"
        else
            echo -e "${BYELLOW}Kernel not recognised.  Please ensure you have support on your system for Atom.${NORM}"
        fi
        if [[ -f $f ]] # Checks to see if file exists in current working directory
        then
            $RUN_COMMAND "${f}"
        else
            $RUN_COMMAND "${HOME}/scripts/bash/${f}"
        fi
    done
}


openCommand() {
    for c in $@
    do
        main "$(command -v "${c}")" # equivalent of oina $(which ${1})
    done
}


while getopts ":-:ch" OPTION; do
    case $OPTION in
        -)
            case $OPTARG in
                help)
                    display_help ;;
                command)
                    openCommand "${@:2}" ;;
                *)
                    opt_err ;;
            esac ;;
        h)
            display_help ;;
        c)
            openCommand "${@:2}" ;;
        *)
          opt_err ;;
    esac
done


# Open file(s)
# if no options passed, curl file into appropriate directory
if [[ $OPTIND -eq 1 ]]
then
    main "${@}"
fi
shift $((OPTIND-1))



clean-exit
