#! /bin/bash

# define bash directory
BASH_DIR="${HOME}/scripts/bash/"

# source required scripts
source ${BASH_DIR}/dependencies/source-dependencies.sh

display_help() {
    help_start 'oinb [option... | file name...]' 'The present script will open a specified file in Brackets.app.  If the file is not found in the current directory, it will look for it in `~/scripts/bash`.  Need to manually run `brew cask install brackets`.'
    help_help '2'
    clean-exit
}


while getopts ":-:h" OPTION; do
    case $OPTION in
        -)
            case $OPTARG in
                help)
                    display_help ;;
                *)
                    opt_err ;;
            esac ;;
        h)
            display_help ;; 
        *)
          opt_err ;;  
    esac
done

for f in $@
do
    if [[ -f $f ]] # Checks to see if file exists in current working directory
    then
        open -a "Brackets.app" $f
    else
        open -a "Brackets.app" ~/scripts/bash/$f
    fi
done


clean-exit
