#! /bin/bash

# define bash directory
BASH_DIR="${HOME}/scripts/bash/"

# source required scripts
source ${BASH_DIR}/dependencies/source-dependencies.sh


# Installing Atom for macOS
[[ $KERNEL == "Darwin" ]] && \
    is-library-then-install "${BREWCASK}"
[[ $KERNEL == "Darwin" ]] && \
    is-app-then-install "${ATOM}"
# Installing Atom for Linux
if [[ $(getconf LONG_BIT) == "64" ]]
then
    if [[ $OS == "debian"  ]]
    then
        cd "${HOME}/Downloads/"
        wget https://github.com/adobe/brackets/releases/download/release-1.14.1/Brackets.Release.1.14.1.64-bit.deb || echo -e "${ERROR_OCCURRED}"
        sudo dpkg -i Brackets.Release.*
        cd - > /dev/null
    fi
    if [[ $OS == "arch" ]]
    then
        aur_install "${BRACKETS}" 'https://aur.archlinux.org/cgit/aur.git/snapshot/brackets.tar.gz'
    fi
elif [[ $(getconf LONG_BIT) == "32" ]]
then
    if [[ $OS == "debian" ]]
    then
        cd "${HOME}/Downloads/"
        wget https://github.com/adobe/brackets/releases/download/release-1.14.1/Brackets.Release.1.14.1.32-bit.deb || echo -e "${ERROR_OCCURRED}" 
        sudo dpkg -i Brackets.Release.*
        sudo apt install ./Brackets.Release.*
        cd - > /dev/null
    else
        echo -e "${BYELLOW}Sorry, you need to manually download Atom on 32-bit systems.${NORM}" && \
        clean-exit
    fi
fi

display_help() {
    help_start 'oinb [option... | file name...]' 'The present script will open a specified file in Brackets.app.  If the file is not found in the current directory, it will look for it in `~/scripts/bash`.  Need to manually run `brew cask install brackets`.'
    help_help '2'
    clean-exit
}


while getopts ":-:h" OPTION; do
    case $OPTION in
        -)
            case $OPTARG in
                help)
                    display_help ;;
                *)
                    opt_err ;;
            esac ;;
        h)
            display_help ;; 
        *)
          opt_err ;;  
    esac
done

for f in $@
do
    if [[ -f $f ]] # Checks to see if file exists in current working directory
    then
        open -a "Brackets.app" $f
    else
        open -a "Brackets.app" ~/scripts/bash/$f
    fi
done


clean-exit
