#! /bin/bash

#ensure you run `brew install pdfgrep` and `brew install coreutils`, and ensure you have python if you use the python method to calculate time

#start=$(python3 -c 'import time; print(time.time())')
start=`gdate +%s.%N` || exit $?

#begin search
pdf_search=$(pdfgrep -ril $1) || exit $?

echo -e "\033[1;38m${pdf_search}\033[0;38m"

#end of search

#calculates runtime (because *nix on os x is bad and doesn't support %N)
#end=$(python3 -c 'import time; print(time.time())')
end=`gdate +%s.%N`

runtime=$(echo "$end - $start" | bc )
pdf_count=$(pdfgrep -ril $1 | wc -l)

echo -e "\033[1;33m$runtime seconds\033[0;38m"

echo -e "\033[1;38;5;2mThe word \"$1\" was found in"${pdf_count}" PDFs\033[0;38m"


#Other meand of calculating runtime:

#python3 -c 'import time; print("%s seconds" % round(time.time()/10000000000, 2))'
#ruby -e 'puts Time.now.to_f/10000000000'#Output in seconds
#php -r 'echo microtime(TRUE)/10000000000;' 
#| perl -MTime::Piece -pe 's/(\d{13})/Time::Piece->localtime($1 \/1000)->strftime("%Y-%m-%d %a")/e'
