#! /bin/bash

trap "exit" INT

# define bash directory
BASH_DIR="${HOME}/scripts/bash/"

# Immediately exits script if nothing is passed to it
if [[ -z "${@}" ]]
then
    HELP="\033[1;33m You must have at least one argument.  Use -h for help. \033[0;38m"
    echo -e "${HELP}"
    exit $?
fi

# source required scripts
source ${BASH_DIR}/dependencies/source-dependencies.sh

# Help
display_help() {
    help_start 'tex-count [option... | /path/to/file]' 'The present script will (mostly accurately) tell you the word count of a PDF.'
    help_help '2'
    clean-exit
}

FIRST_PARAM=${1}
word-count-function() {
    pdftotext "${FIRST_PARAM}.pdf" - | \
    egrep -e '\w\w\w+' | \
    iconv -f ISO-8859-15 -t UTF-8 | \
    wc -w
}


# Options
while getopts ":-:h" OPTION; do
        case $OPTION in
                -)
                    case $OPTARG in
                        help)
                            display_help ;;
                        *)
                            opt_err ;;
                    esac ;;
                h)
                    display_help ;;
                *)
                    opt_err ;;
        esac
done


# If no options
[[ $OPTIND -eq 1 ]] && word-count-function


# Clean up
clean-exit
